

DECLARE @DATABASE_SOURCE AS VARCHAR(30)
SET @DATABASE_SOURCE = 'DW_CRM_MIGRATION' -- EX: AdventureWorks
DECLARE @DATABASE_TARGET varchar(30)
SET @DATABASE_TARGET='DW_CRM_MIGRATION_HOLDING'
DECLARE @STRSQL VARCHAR(MAX)


EXEC ('USE ' +@DATABASE_SOURCE)

DECLARE JOB_CURSOR CURSOR FOR

--SELECT OBJECT_ID FROM SYS.OBJECTS WHERE (([TYPE]='P' AND name LIKE 'USP_DATA_MIG%') OR ([TYPE]='V' AND name LIKE 'uvw_%') )

SELECT name FROM DW_CRM_MIGRATION.dbo.SYSOBJECTS WHERE ([TYPE]='U' AND name LIKE 'SF_%')

OPEN JOB_CURSOR
DECLARE @TABLE_NAME AS VARCHAR(100)
FETCH NEXT FROM JOB_CURSOR
INTO @TABLE_NAME

DECLARE @SQL AS VARCHAR(MAX)

    WHILE @@FETCH_STATUS = 0
    BEGIN


        --PART 1 DROP OBJECT
        SELECT @SQL = N'IF OBJECT_ID (''['+ @TABLE_NAME + ']'') IS NOT NULL 
BEGIN
DROP  TABLE '+@TABLE_NAME+' END' +  CHAR(13) + CHAR(10) +
                    'SELECT TOP 0 * INTO '+@TABLE_NAME+' FROM '+@DATABASE_SOURCE+'.dbo.'+@TABLE_NAME   
                        
        
        --PRINT @SQL
         SET @SQL=REPLACE(@SQL, '''', '''''');
		 SET @STRSQL = N'EXEC '+@DATABASE_TARGET+'.dbo.sp_executesql N''' + @SQL + '''';
        
		--PRINT @STRSQL
		EXECUTE(@STRSQL)

	
			

     FETCH NEXT FROM JOB_CURSOR
     INTO @TABLE_NAME
    END

CLOSE JOB_CURSOR
DEALLOCATE JOB_CURSOR





